export const FETCHING_USERS = "FETCHING_USERS";
export const FETCHING_USERS_SUCCESS = "FETCHING_USERS_SUCCESS";
export const FETCHING_USERS_FAILED = "FETCHING_USERS_FAILED";
export const EDIT_USER = "EDIT_USER";
export const USER_UPDATED = "USER_UPDATED";
